#!/bin/sh -


AWS_ACCESS_ID=`/usr/bin/etcdctl get /_arken.io/config/aws/id`
AWS_ACCESS_SECRET=`/usr/bin/etcdctl get /_arken.io/config/aws/secret`

docker run -e AWS_ACCESS_ID=$AWS_ACCESS_ID -e AWS_ACCESS_SECRET=$AWS_ACCESS_SECRET --rm quay.io/nuxeoio/awscli $@
